services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=db_name
      - DATABASE_USER=root
      - DATABASE_PASSWORD=password
    depends_on:
      - db
    networks:
      site_network:
        ipv4_address: 172.55.0.32

  db:
    image: mariadb
    environment:
      - MYSQL_DATADASE=db_name
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      site_network:
        ipv4_address: 172.55.0.33

  open-appsec-agent:
    image: ghcr.io/openappsec/agent:latest
    container_name: open-appsec-agent
    ipc: host
    environment:
      - registered_server=NGINX
      - AGENT_TOKEN=cp-86805938-a702-4815-85ed-6f75b4c6ececfb08542e-576a-4620-907b-e9356c4f8495
    volumes:
      - ./openappsec/config:/etc/cp/conf
      - ./openappsec/data:/etc/cp/data
      - ./openappsec/debug:/etc/cp/nano_agent
    networks:
      - site_network

  open-appsec-nginx:
    image: ghcr.io/openappsec/nginx-attachment:latest
    container_name: open-appsec-nginx
    depends_on:
      - web
      - open-appsec-agent
    ipc: host
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      site_network:
        ipv4_address: 172.55.0.34

volumes:
  db_data:

networks:
  site_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.55.0.0/16